# TODO copyed from pytest
[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=61",
    "setuptools-scm[toml]>=6.2.3",
]

[project]
dynamic = ["version"]
name = "pytest-directives"
description = ""
readme = "README.md"
keywords = [
]
dependencies = [
]